---
title: "Noruega"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(GGally)
library(NbClust)
library(igraph)
library(factoextra)
library(corrplot)
library(explore)
```

```{r}
demog_data <- read.table("data/multivariate.csv",
                         header = T, sep = ";")
colnames(demog_data) <- gsub("\\.", "_", colnames(demog_data))
colnames(demog_data)
names(demog_data)[9] <- "Population_aged_65"
head(demog_data, 3)
```

```{r}
demog_data |> explore_all()
summary(demog_data)
```

```{r}
demo_cuanti <- demog_data |>
   select(Pop, Birth_rate, Mortality_rate, Life_expectancy,
          Infant_mortality, Children_per_woman,  Growth_rate,
          Population_aged_65) |>
   na.omit()
```

```{r}
demo_cuanti |> 
   ggpairs(progress = FALSE)
```

```{r}
demo_cuanti |> 
  cor() |> 
  corrplot.mixed(order = 'AOE')
```

```{r}
demog_data  |>
  ggplot(aes(x = Growth_rate, y = Life_expectancy)) +
  geom_point() +
  labs(title = "Esperanza de vida vs. Tasa de crecimiento",
       x = "Tasa de crecimiento",
       y = "Esperanza de vida") +
  theme_minimal()
```

```{r}
demog_data  |>
  ggplot(aes(x = Growth_rate, y = Life_expectancy, size = Pop,
             color = Continent)) +
  geom_point(alpha=0.5) +
  scale_size(range = c(.1, 20)) +
  labs(title = "De Europa a Norteamérica, Oceanía, Sudamérica y África, a través de Asia",
       x = "Tasa de crecimiento",
       y = "Esperanza de vida") +
  theme_minimal() +
  theme(axis.title.x = element_text(hjust = 0),
        axis.title.y = element_text(hjust = 1))
```

```{r}
demog_scatter <- ggplot(data = demog_data, # data
              aes(x = Growth_rate, y = Life_expectancy, colour = Continent)) + #aesthetics
    geom_point(alpha = 0.5) + #geometries
    facet_wrap(~ Continent, scales = "free") + #facets
    labs(title = "Life expectancy at birth vs. Per capita GDP", 
         x = "Growth_rate", y = "Life_expectancy", colour = "Continent") + #labels
    theme_light() #themes

demog_scatter 
```

```{r}
demog_scatter_escala <- ggplot(data = demog_data,
                               aes(x = Growth_rate,
                                   y = Life_expectancy,
                                   colour = Continent)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~ Continent, scales = "free") +
  labs(title = "Esperanza de vida respecto al PIB per capita",
       x = "Tasa de crecimiento", y = "Esperanza de vida",
       colour = "Continent") +
  scale_x_continuous(limits = c(-10, 45)) +
  scale_y_continuous(limits = c(45, 85)) +
  theme_light()

demog_scatter_escala 
```

```{r}
demog_scatter_escala + geom_smooth(method = NULL, se = TRUE)
```

